#!/bin/bash
# Shell wrapper for supporting installing with different backends for CMake < 3.13
# SPDX-License-Identifier: MIT

# Collect arguments
__cmake_builddir="$(realpath $1)"
__cmake_destdir="$2"

if [ -f "${__cmake_builddir}/Makefile" ]; then
	/usr/bin/make -C "${__cmake_builddir}" install DESTDIR="${__cmake_destdir}"
	exit $?
elif [ -f "${__cmake_builddir}/build.ninja" ]; then
	DESTDIR="${__cmake_destdir}" /usr/bin/ninja -C "${__cmake_builddir}" install -v
	exit $?
else
	echo "Unknown build format, exiting!"
	exit 99
fi
